version: '3'


services:
    mysql_db:
        container_name: mysql_db
        image: "mysql:8.0"
        environment: 
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_DATABASE=${MYSQL_DB}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]
            interval: 3s
            timeout: 20s
            retries: 8

    web:
        container_name: web
        build:
            context: ../api
            dockerfile: ../docker/dockerfiles/api
        ports:
            - ":4000"
        volumes:
            - ../api:/code
        environment:
            - DB_USER=${MYSQL_USER}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - DB_NAME=${MYSQL_DB}
            - DB_HOST=mysql_db
            - DB_PORT=3306
        depends_on:
            mysql_db:
                condition: service_healthy
        tty: true

    nginx:
        container_name: nginx
        build:
            context: ./
            dockerfile: ./dockerfiles/nginx
        restart: always
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./ssl:/etc/nginx/ssl
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - web

    